default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  user: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "Personlist_development") %>

test:
  <<: *default
  database: Personlist_test

production:
  <<: *default
  database: Personlist_production
  username: Personlist
  password: <%= ENV['PERSONLIST_DATABASE_PASSWORD'] %>
